### ISSUE TITLE
Collecting FSA details in Tamilnadu

### ISSUE THREAD

**Issue by iamVP7** [MozillaTN/Task-Force-Team#2]
## Goal: 
To Collect all FSA details of Tamilnadu

## Success:
One point of information in Github and is easier to contact them

## Roles:
Owner:  @hellokarthic

## Required: 
The details to be collected are 
* Club Name
* Club Lead Name
* Club Founder Name
* FSA's in Club
* Website made (prefer Github website)
* All FSA contributors Blogs
* University/College
* City
*  E-mail ID
* Twitter ID, Facebook page (optional) 

## What to do:
With all these details create a wiki, in this repo. So we can easy check when we require. We can easily passinfo in to them through Mail or Telegram.

**Comment by hellokarthic** [comment]
1.Is this FSA details or Club Details? bcoz all data is related to clubs and not of an FSA 
2.What if the FSA has no club in his/her college?
3. What if the FSA has completed his College & no longer a part of his college club?
4. Do we need to collect info through google forms and put them neatly in a place?
5. Are all these info needs to be mandatory?
6. Is this data to be publicly available? or only for a closed reference?

**Comment by iamVP7** [comment]
1.Is this FSA details or Club Details? bcoz all data is related to clubs and not of an FSA
     Anyone when he is a FSA, he will be representing a College mostly. So based on Club.
2.What if the FSA has no club in his/her college?
      No issues just College name is enough
3. What if the FSA has completed his College & no longer a part of his college club?
       We will ping him at the end of May and check who is going to take over after him.
4. Do we need to collect info through google forms and put them neatly in a place?
        The plan is to use this repo wiki, to display the info. Its better to send through Mail I guess. But if you feel Google form is easier prefer it then. But before making it here, use Google writer so we can check what we missed.
5. Are all these info needs to be mandatory?
        Not all are required, in general we need a point of contact from that college to know what happens there.
6. Is this data to be publicly available? or only for a closed reference?
        As said before we will be making some data Public, will discuss regarding that in DM.

**Comment by hellokarthic** [comment]
FSA Tamilnadu Database link;
http://goo.gl/forms/aKYlUFc9bU

Each and every Mozilla Volunteer from tamilnadu is asked to fill this form.
This is for internal use only.

Issue Closed.
